#include <iostream>
#include <unordered_set>
#include <string>
#include <vector>
#include <iterator>
#include "gmock/gmock.h"
#include "solution.cpp"


using namespace std;


TEST(Solution, default) {
    Solution s;
    unordered_set<string> wordList;
    wordList.insert(string("hot"));
    wordList.insert(string("dot"));
    wordList.insert(string("dog"));
    wordList.insert(string("lot"));
    wordList.insert(string("log"));
    vector<vector<string> > result;
    result = s.findLadders(string("hit"), string("cog"), wordList);
    ASSERT_EQ(2, result.size());
    ASSERT_EQ(5, result[0].size());
}

TEST(Solution, no_path)
{
    Solution s;
    unordered_set<string> wordList;
    vector<vector<string> > result;
    result = s.findLadders(string("hit"), string("cog"), wordList);
    ASSERT_EQ(0, result.size());
}

TEST(Solution, begin_to_end_directly)
{
    Solution s;
    unordered_set<string> wordList;
    vector<vector<string> > result;
    result = s.findLadders(string("hit"), string("hot"), wordList);
    ASSERT_EQ(1, result.size());
    ASSERT_EQ(2, result[0].size());
}

TEST(Solution, TLE)
{
    Solution s;
    unordered_set<string> wordList;
    wordList.insert("si");
    wordList.insert("go");
    wordList.insert("se");
    wordList.insert("cm");
    wordList.insert("so");
    wordList.insert("ph");
    wordList.insert("mt");
    wordList.insert("db");
    wordList.insert("mb");
    wordList.insert("sb");
    wordList.insert("kr");
    wordList.insert("ln");
    wordList.insert("tm");
    wordList.insert("le");
    wordList.insert("av");
    wordList.insert("sm");
    wordList.insert("ar");
    wordList.insert("ci");
    wordList.insert("ca");
    wordList.insert("br");
    wordList.insert("ti");
    wordList.insert("ba");
    wordList.insert("to");
    wordList.insert("ra");
    wordList.insert("fa");
    wordList.insert("yo");
    wordList.insert("ow");
    wordList.insert("sn");
    wordList.insert("ya");
    wordList.insert("cr");
    wordList.insert("po");
    wordList.insert("fe");
    wordList.insert("ho");
    wordList.insert("ma");
    wordList.insert("re");
    wordList.insert("or");
    wordList.insert("rn");
    wordList.insert("au");
    wordList.insert("ur");
    wordList.insert("rh");
    wordList.insert("sr");
    wordList.insert("tc");
    wordList.insert("lt");
    wordList.insert("lo");
    wordList.insert("as");
    wordList.insert("fr");
    wordList.insert("nb");
    wordList.insert("yb");
    wordList.insert("if");
    wordList.insert("pb");
    wordList.insert("ge");
    wordList.insert("th");
    wordList.insert("pm");
    wordList.insert("rb");
    wordList.insert("sh");
    wordList.insert("co");
    wordList.insert("ga");
    wordList.insert("li");
    wordList.insert("ha");
    wordList.insert("hz");
    wordList.insert("no");
    wordList.insert("bi");
    wordList.insert("di");
    wordList.insert("hi");
    wordList.insert("qa");
    wordList.insert("pi");
    wordList.insert("os");
    wordList.insert("uh");
    wordList.insert("wm");
    wordList.insert("an");
    wordList.insert("me");
    wordList.insert("mo");
    wordList.insert("na");
    wordList.insert("la");
    wordList.insert("st");
    wordList.insert("er");
    wordList.insert("sc");
    wordList.insert("ne");
    wordList.insert("mn");
    wordList.insert("mi");
    wordList.insert("am");
    wordList.insert("ex");
    wordList.insert("pt");
    wordList.insert("io");
    wordList.insert("be");
    wordList.insert("fm");
    wordList.insert("ta");
    wordList.insert("tb");
    wordList.insert("ni");
    wordList.insert("mr");
    wordList.insert("pa");
    wordList.insert("he");
    wordList.insert("lr");
    wordList.insert("sq");
    wordList.insert("ye");
    vector<vector<string> > result;
    result = s.findLadders(string("qa"), string("sq"), wordList);
    ASSERT_EQ(51, result.size());
}

TEST(Solution, SIX_HUNDRED_WORDS)
{
    Solution s;
    unordered_set<string> wordList;

    wordList.insert("kid" );
    wordList.insert("tag" );
    wordList.insert("pup" );
    wordList.insert("ail" );
    wordList.insert("tun" );
    wordList.insert("woo" );
    wordList.insert("erg" );
    wordList.insert("luz" );
    wordList.insert("brr" );
    wordList.insert("gay" );
    wordList.insert("sip" );
    wordList.insert("kay" );
    wordList.insert("per" );
    wordList.insert("val" );
    wordList.insert("mes" );
    wordList.insert("ohs" );
    wordList.insert("now" );
    wordList.insert("boa" );
    wordList.insert("cet" );
    wordList.insert("pal" );
    wordList.insert("bar" );
    wordList.insert("die" );
    wordList.insert("war" );
    wordList.insert("hay" );
    wordList.insert("eco" );
    wordList.insert("pub" );
    wordList.insert("lob" );
    wordList.insert("rue" );
    wordList.insert("fry" );
    wordList.insert("lit" );
    wordList.insert("rex" );
    wordList.insert("jan" );
    wordList.insert("cot" );
    wordList.insert("bid" );
    wordList.insert("ali" );
    wordList.insert("pay" );
    wordList.insert("col" );
    wordList.insert("gum" );
    wordList.insert("ger" );
    wordList.insert("row" );
    wordList.insert("won" );
    wordList.insert("dan" );
    wordList.insert("rum" );
    wordList.insert("fad" );
    wordList.insert("tut" );
    wordList.insert("sag" );
    wordList.insert("yip" );
    wordList.insert("sui" );
    wordList.insert("ark" );
    wordList.insert("has" );
    wordList.insert("zip" );
    wordList.insert("fez" );
    wordList.insert("own" );
    wordList.insert("ump" );
    wordList.insert("dis" );
    wordList.insert("ads" );
    wordList.insert("max" );
    wordList.insert("jaw" );
    wordList.insert("out" );
    wordList.insert("btu" );
    wordList.insert("ana" );
    wordList.insert("gap" );
    wordList.insert("cry" );
    wordList.insert("led" );
    wordList.insert("abe" );
    wordList.insert("box" );
    wordList.insert("ore" );
    wordList.insert("pig" );
    wordList.insert("fie" );
    wordList.insert("toy" );
    wordList.insert("fat" );
    wordList.insert("cal" );
    wordList.insert("lie" );
    wordList.insert("noh" );
    wordList.insert("sew" );
    wordList.insert("ono" );
    wordList.insert("tam" );
    wordList.insert("flu" );
    wordList.insert("mgm" );
    wordList.insert("ply" );
    wordList.insert("awe" );
    wordList.insert("pry" );
    wordList.insert("tit" );
    wordList.insert("tie" );
    wordList.insert("yet" );
    wordList.insert("too" );
    wordList.insert("tax" );
    wordList.insert("jim" );
    wordList.insert("san" );
    wordList.insert("pan" );
    wordList.insert("map" );
    wordList.insert("ski" );
    wordList.insert("ova" );
    wordList.insert("wed" );
    wordList.insert("non" );
    wordList.insert("wac" );
    wordList.insert("nut" );
    wordList.insert("why" );
    wordList.insert("bye" );
    wordList.insert("lye" );
    wordList.insert("oct" );
    wordList.insert("old" );
    wordList.insert("fin" );
    wordList.insert("feb" );
    wordList.insert("chi" );
    wordList.insert("sap" );
    wordList.insert("owl" );
    wordList.insert("log" );
    wordList.insert("tod" );
    wordList.insert("dot" );
    wordList.insert("bow" );
    wordList.insert("fob" );
    wordList.insert("for" );
    wordList.insert("joe" );
    wordList.insert("ivy" );
    wordList.insert("fan" );
    wordList.insert("age" );
    wordList.insert("fax" );
    wordList.insert("hip" );
    wordList.insert("jib" );
    wordList.insert("mel" );
    wordList.insert("hus" );
    wordList.insert("sob" );
    wordList.insert("ifs" );
    wordList.insert("tab" );
    wordList.insert("ara" );
    wordList.insert("dab" );
    wordList.insert("jag" );
    wordList.insert("jar" );
    wordList.insert("arm" );
    wordList.insert("lot" );
    wordList.insert("tom" );
    wordList.insert("sax" );
    wordList.insert("tex" );
    wordList.insert("yum" );
    wordList.insert("pei" );
    wordList.insert("wen" );
    wordList.insert("wry" );
    wordList.insert("ire" );
    wordList.insert("irk" );
    wordList.insert("far" );
    wordList.insert("mew" );
    wordList.insert("wit" );
    wordList.insert("doe" );
    wordList.insert("gas" );
    wordList.insert("rte" );
    wordList.insert("ian" );
    wordList.insert("pot" );
    wordList.insert("ask" );
    wordList.insert("wag" );
    wordList.insert("hag" );
    wordList.insert("amy" );
    wordList.insert("nag" );
    wordList.insert("ron" );
    wordList.insert("soy" );
    wordList.insert("gin" );
    wordList.insert("don" );
    wordList.insert("tug" );
    wordList.insert("fay" );
    wordList.insert("vic" );
    wordList.insert("boo" );
    wordList.insert("nam" );
    wordList.insert("ave" );
    wordList.insert("buy" );
    wordList.insert("sop" );
    wordList.insert("but" );
    wordList.insert("orb" );
    wordList.insert("fen" );
    wordList.insert("paw" );
    wordList.insert("his" );
    wordList.insert("sub" );
    wordList.insert("bob" );
    wordList.insert("yea" );
    wordList.insert("oft" );
    wordList.insert("inn" );
    wordList.insert("rod" );
    wordList.insert("yam" );
    wordList.insert("pew" );
    wordList.insert("web" );
    wordList.insert("hod" );
    wordList.insert("hun" );
    wordList.insert("gyp" );
    wordList.insert("wei" );
    wordList.insert("wis" );
    wordList.insert("rob" );
    wordList.insert("gad" );
    wordList.insert("pie" );
    wordList.insert("mon" );
    wordList.insert("dog" );
    wordList.insert("bib" );
    wordList.insert("rub" );
    wordList.insert("ere" );
    wordList.insert("dig" );
    wordList.insert("era" );
    wordList.insert("cat" );
    wordList.insert("fox" );
    wordList.insert("bee" );
    wordList.insert("mod" );
    wordList.insert("day" );
    wordList.insert("apr" );
    wordList.insert("vie" );
    wordList.insert("nev" );
    wordList.insert("jam" );
    wordList.insert("pam" );
    wordList.insert("new" );
    wordList.insert("aye" );
    wordList.insert("ani" );
    wordList.insert("and" );
    wordList.insert("ibm" );
    wordList.insert("yap" );
    wordList.insert("can" );
    wordList.insert("pyx" );
    wordList.insert("tar" );
    wordList.insert("kin" );
    wordList.insert("fog" );
    wordList.insert("hum" );
    wordList.insert("pip" );
    wordList.insert("cup" );
    wordList.insert("dye" );
    wordList.insert("lyx" );
    wordList.insert("jog" );
    wordList.insert("nun" );
    wordList.insert("par" );
    wordList.insert("wan" );
    wordList.insert("fey" );
    wordList.insert("bus" );
    wordList.insert("oak" );
    wordList.insert("bad" );
    wordList.insert("ats" );
    wordList.insert("set" );
    wordList.insert("qom" );
    wordList.insert("vat" );
    wordList.insert("eat" );
    wordList.insert("pus" );
    wordList.insert("rev" );
    wordList.insert("axe" );
    wordList.insert("ion" );
    wordList.insert("six" );
    wordList.insert("ila" );
    wordList.insert("lao" );
    wordList.insert("mom" );
    wordList.insert("mas" );
    wordList.insert("pro" );
    wordList.insert("few" );
    wordList.insert("opt" );
    wordList.insert("poe" );
    wordList.insert("art" );
    wordList.insert("ash" );
    wordList.insert("oar" );
    wordList.insert("cap" );
    wordList.insert("lop" );
    wordList.insert("may" );
    wordList.insert("shy" );
    wordList.insert("rid" );
    wordList.insert("bat" );
    wordList.insert("sum" );
    wordList.insert("rim" );
    wordList.insert("fee" );
    wordList.insert("bmw" );
    wordList.insert("sky" );
    wordList.insert("maj" );
    wordList.insert("hue" );
    wordList.insert("thy" );
    wordList.insert("ava" );
    wordList.insert("rap" );
    wordList.insert("den" );
    wordList.insert("fla" );
    wordList.insert("auk" );
    wordList.insert("cox" );
    wordList.insert("ibo" );
    wordList.insert("hey" );
    wordList.insert("saw" );
    wordList.insert("vim" );
    wordList.insert("sec" );
    wordList.insert("ltd" );
    wordList.insert("you" );
    wordList.insert("its" );
    wordList.insert("tat" );
    wordList.insert("dew" );
    wordList.insert("eva" );
    wordList.insert("tog" );
    wordList.insert("ram" );
    wordList.insert("let" );
    wordList.insert("see" );
    wordList.insert("zit" );
    wordList.insert("maw" );
    wordList.insert("nix" );
    wordList.insert("ate" );
    wordList.insert("gig" );
    wordList.insert("rep" );
    wordList.insert("owe" );
    wordList.insert("ind" );
    wordList.insert("hog" );
    wordList.insert("eve" );
    wordList.insert("sam" );
    wordList.insert("zoo" );
    wordList.insert("any" );
    wordList.insert("dow" );
    wordList.insert("cod" );
    wordList.insert("bed" );
    wordList.insert("vet" );
    wordList.insert("ham" );
    wordList.insert("sis" );
    wordList.insert("hex" );
    wordList.insert("via" );
    wordList.insert("fir" );
    wordList.insert("nod" );
    wordList.insert("mao" );
    wordList.insert("aug" );
    wordList.insert("mum" );
    wordList.insert("hoe" );
    wordList.insert("bah" );
    wordList.insert("hal" );
    wordList.insert("keg" );
    wordList.insert("hew" );
    wordList.insert("zed" );
    wordList.insert("tow" );
    wordList.insert("gog" );
    wordList.insert("ass" );
    wordList.insert("dem" );
    wordList.insert("who" );
    wordList.insert("bet" );
    wordList.insert("gos" );
    wordList.insert("son" );
    wordList.insert("ear" );
    wordList.insert("spy" );
    wordList.insert("kit" );
    wordList.insert("boy" );
    wordList.insert("due" );
    wordList.insert("sen" );
    wordList.insert("oaf" );
    wordList.insert("mix" );
    wordList.insert("hep" );
    wordList.insert("fur" );
    wordList.insert("ada" );
    wordList.insert("bin" );
    wordList.insert("nil" );
    wordList.insert("mia" );
    wordList.insert("ewe" );
    wordList.insert("hit" );
    wordList.insert("fix" );
    wordList.insert("sad" );
    wordList.insert("rib" );
    wordList.insert("eye" );
    wordList.insert("hop" );
    wordList.insert("haw" );
    wordList.insert("wax" );
    wordList.insert("mid" );
    wordList.insert("tad" );
    wordList.insert("ken" );
    wordList.insert("wad" );
    wordList.insert("rye" );
    wordList.insert("pap" );
    wordList.insert("bog" );
    wordList.insert("gut" );
    wordList.insert("ito" );
    wordList.insert("woe" );
    wordList.insert("our" );
    wordList.insert("ado" );
    wordList.insert("sin" );
    wordList.insert("mad" );
    wordList.insert("ray" );
    wordList.insert("hon" );
    wordList.insert("roy" );
    wordList.insert("dip" );
    wordList.insert("hen" );
    wordList.insert("iva" );
    wordList.insert("lug" );
    wordList.insert("asp" );
    wordList.insert("hui" );
    wordList.insert("yak" );
    wordList.insert("bay" );
    wordList.insert("poi" );
    wordList.insert("yep" );
    wordList.insert("bun" );
    wordList.insert("try" );
    wordList.insert("lad" );
    wordList.insert("elm" );
    wordList.insert("nat" );
    wordList.insert("wyo" );
    wordList.insert("gym" );
    wordList.insert("dug" );
    wordList.insert("toe" );
    wordList.insert("dee" );
    wordList.insert("wig" );
    wordList.insert("sly" );
    wordList.insert("rip" );
    wordList.insert("geo" );
    wordList.insert("cog" );
    wordList.insert("pas" );
    wordList.insert("zen" );
    wordList.insert("odd" );
    wordList.insert("nan" );
    wordList.insert("lay" );
    wordList.insert("pod" );
    wordList.insert("fit" );
    wordList.insert("hem" );
    wordList.insert("joy" );
    wordList.insert("bum" );
    wordList.insert("rio" );
    wordList.insert("yon" );
    wordList.insert("dec" );
    wordList.insert("leg" );
    wordList.insert("put" );
    wordList.insert("sue" );
    wordList.insert("dim" );
    wordList.insert("pet" );
    wordList.insert("yaw" );
    wordList.insert("nub" );
    wordList.insert("bit" );
    wordList.insert("bur" );
    wordList.insert("sid" );
    wordList.insert("sun" );
    wordList.insert("oil" );
    wordList.insert("red" );
    wordList.insert("doc" );
    wordList.insert("moe" );
    wordList.insert("caw" );
    wordList.insert("eel" );
    wordList.insert("dix" );
    wordList.insert("cub" );
    wordList.insert("end" );
    wordList.insert("gem" );
    wordList.insert("off" );
    wordList.insert("yew" );
    wordList.insert("hug" );
    wordList.insert("pop" );
    wordList.insert("tub" );
    wordList.insert("sgt" );
    wordList.insert("lid" );
    wordList.insert("pun" );
    wordList.insert("ton" );
    wordList.insert("sol" );
    wordList.insert("din" );
    wordList.insert("yup" );
    wordList.insert("jab" );
    wordList.insert("pea" );
    wordList.insert("bug" );
    wordList.insert("gag" );
    wordList.insert("mil" );
    wordList.insert("jig" );
    wordList.insert("hub" );
    wordList.insert("low" );
    wordList.insert("did" );
    wordList.insert("tin" );
    wordList.insert("get" );
    wordList.insert("gte" );
    wordList.insert("sox" );
    wordList.insert("lei" );
    wordList.insert("mig" );
    wordList.insert("fig" );
    wordList.insert("lon" );
    wordList.insert("use" );
    wordList.insert("ban" );
    wordList.insert("flo" );
    wordList.insert("nov" );
    wordList.insert("jut" );
    wordList.insert("bag" );
    wordList.insert("mir" );
    wordList.insert("sty" );
    wordList.insert("lap" );
    wordList.insert("two" );
    wordList.insert("ins" );
    wordList.insert("con" );
    wordList.insert("ant" );
    wordList.insert("net" );
    wordList.insert("tux" );
    wordList.insert("ode" );
    wordList.insert("stu" );
    wordList.insert("mug" );
    wordList.insert("cad" );
    wordList.insert("nap" );
    wordList.insert("gun" );
    wordList.insert("fop" );
    wordList.insert("tot" );
    wordList.insert("sow" );
    wordList.insert("sal" );
    wordList.insert("sic" );
    wordList.insert("ted" );
    wordList.insert("wot" );
    wordList.insert("del" );
    wordList.insert("imp" );
    wordList.insert("cob" );
    wordList.insert("way" );
    wordList.insert("ann" );
    wordList.insert("tan" );
    wordList.insert("mci" );
    wordList.insert("job" );
    wordList.insert("wet" );
    wordList.insert("ism" );
    wordList.insert("err" );
    wordList.insert("him" );
    wordList.insert("all" );
    wordList.insert("pad" );
    wordList.insert("hah" );
    wordList.insert("hie" );
    wordList.insert("aim" );
    wordList.insert("ike" );
    wordList.insert("jed" );
    wordList.insert("ego" );
    wordList.insert("mac" );
    wordList.insert("baa" );
    wordList.insert("min" );
    wordList.insert("com" );
    wordList.insert("ill" );
    wordList.insert("was" );
    wordList.insert("cab" );
    wordList.insert("ago" );
    wordList.insert("ina" );
    wordList.insert("big" );
    wordList.insert("ilk" );
    wordList.insert("gal" );
    wordList.insert("tap" );
    wordList.insert("duh" );
    wordList.insert("ola" );
    wordList.insert("ran" );
    wordList.insert("lab" );
    wordList.insert("top" );
    wordList.insert("gob" );
    wordList.insert("hot" );
    wordList.insert("ora" );
    wordList.insert("tia" );
    wordList.insert("kip" );
    wordList.insert("han" );
    wordList.insert("met" );
    wordList.insert("hut" );
    wordList.insert("she" );
    wordList.insert("sac" );
    wordList.insert("fed" );
    wordList.insert("goo" );
    wordList.insert("tee" );
    wordList.insert("ell" );
    wordList.insert("not" );
    wordList.insert("act" );
    wordList.insert("gil" );
    wordList.insert("rut" );
    wordList.insert("ala" );
    wordList.insert("ape" );
    wordList.insert("rig" );
    wordList.insert("cid" );
    wordList.insert("god" );
    wordList.insert("duo" );
    wordList.insert("lin" );
    wordList.insert("aid" );
    wordList.insert("gel" );
    wordList.insert("awl" );
    wordList.insert("lag" );
    wordList.insert("elf" );
    wordList.insert("liz" );
    wordList.insert("ref" );
    wordList.insert("aha" );
    wordList.insert("fib" );
    wordList.insert("oho" );
    wordList.insert("tho" );
    wordList.insert("her" );
    wordList.insert("nor" );
    wordList.insert("ace" );
    wordList.insert("adz" );
    wordList.insert("fun" );
    wordList.insert("ned" );
    wordList.insert("coo" );
    wordList.insert("win" );
    wordList.insert("tao" );
    wordList.insert("coy" );
    wordList.insert("van" );
    wordList.insert("man" );
    wordList.insert("pit" );
    wordList.insert("guy" );
    wordList.insert("foe" );
    wordList.insert("hid" );
    wordList.insert("mai" );
    wordList.insert("sup" );
    wordList.insert("jay" );
    wordList.insert("hob" );
    wordList.insert("mow" );
    wordList.insert("jot" );
    wordList.insert("are" );
    wordList.insert("pol" );
    wordList.insert("arc" );
    wordList.insert("lax" );
    wordList.insert("aft" );
    wordList.insert("alb" );
    wordList.insert("len" );
    wordList.insert("air" );
    wordList.insert("pug" );
    wordList.insert("pox" );
    wordList.insert("vow" );
    wordList.insert("got" );
    wordList.insert("meg" );
    wordList.insert("zoe" );
    wordList.insert("amp" );
    wordList.insert("ale" );
    wordList.insert("bud" );
    wordList.insert("gee" );
    wordList.insert("pin" );
    wordList.insert("dun" );
    wordList.insert("pat" );
    wordList.insert("ten" );
    wordList.insert("mob" );
    vector<vector<string> > result;
    result = s.findLadders(string("cet"), string("ism"), wordList);
    ASSERT_EQ(3, result.size());
}
